ALTER TABLE accounts ADD COLUMN IF NOT EXISTS first_name VARCHAR(255);
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS last_name VARCHAR(255);
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(1024);
